/*
 * model-parameters/model_metadata.h  — stub for MangoGuard unified library
 *
 * The Edge Impulse SDK (ei_classifier_types.h) unconditionally includes
 * "model-parameters/model_metadata.h".  In a normal single-model library
 * this file is generated by Edge Impulse.  In this unified library the real
 * metadata lives in model-parameters-health/ and model-parameters-forecast/.
 *
 * We satisfy the SDK's hard-coded include by providing the minimum
 * EI_CLASSIFIER_* defines it needs to compile.  We use the health-model
 * values as the "default" because they are the most demanding (camera,
 * largest arena, etc.).  At runtime both models are driven through their
 * own ei_impulse_handle_t handles, so these compile-time globals are only
 * used for struct sizing — label_count = 3 is correct for both models.
 */

#ifndef _MG_STUB_MODEL_METADATA_H_
#define _MG_STUB_MODEL_METADATA_H_

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* ── Shared enum constants ─────────────────────────────────────────────── */
#ifndef EI_CLASSIFIER_NONE
#define EI_CLASSIFIER_NONE                       255
#define EI_CLASSIFIER_UTENSOR                    1
#define EI_CLASSIFIER_TFLITE                     2
#define EI_CLASSIFIER_CUBEAI                     3
#define EI_CLASSIFIER_TFLITE_FULL                4
#define EI_CLASSIFIER_TENSAIFLOW                 5
#define EI_CLASSIFIER_TENSORRT                   6
#define EI_CLASSIFIER_DRPAI                      7
#define EI_CLASSIFIER_TFLITE_TIDL                8
#define EI_CLASSIFIER_AKIDA                      9
#define EI_CLASSIFIER_SYNTIANT                   10
#define EI_CLASSIFIER_ONNX_TIDL                  11
#define EI_CLASSIFIER_MEMRYX                     12
#define EI_CLASSIFIER_ETHOS_LINUX                13
#define EI_CLASSIFIER_ATON                       14
#define EI_CLASSIFIER_CEVA_NPN                   15
#define EI_CLASSIFIER_NORDIC_AXON                16
#define EI_CLASSIFIER_VLM_CONNECTOR              17

#define EI_CLASSIFIER_SENSOR_UNKNOWN             255
#define EI_CLASSIFIER_SENSOR_MICROPHONE          1
#define EI_CLASSIFIER_SENSOR_ACCELEROMETER       2
#define EI_CLASSIFIER_SENSOR_CAMERA              3
#define EI_CLASSIFIER_SENSOR_9DOF                4
#define EI_CLASSIFIER_SENSOR_ENVIRONMENTAL       5
#define EI_CLASSIFIER_SENSOR_FUSION              6

#define EI_ANOMALY_TYPE_UNKNOWN                  0
#define EI_ANOMALY_TYPE_KMEANS                   1
#define EI_ANOMALY_TYPE_GMM                      2
#define EI_ANOMALY_TYPE_VISUAL_GMM               3
#define EI_ANOMALY_TYPE_VISUAL_PATCHCORE         4
#define EI_ANOMALY_TYPE_CUSTOM                   5
#define EI_ANOMALY_TYPE_VISUAL_CUSTOM            6

#define EI_CLASSIFIER_DATATYPE_FLOAT32           1
#define EI_CLASSIFIER_DATATYPE_UINT8             3
#define EI_CLASSIFIER_DATATYPE_INT8              9

#define EI_CLASSIFIER_RESIZE_NONE                0
#define EI_CLASSIFIER_RESIZE_FIT_SHORTEST        1
#define EI_CLASSIFIER_RESIZE_FIT_LONGEST         2
#define EI_CLASSIFIER_RESIZE_SQUASH              3

#define EI_CLASSIFIER_LAST_LAYER_UNKNOWN         -1
#define EI_CLASSIFIER_LAST_LAYER_SSD             1
#define EI_CLASSIFIER_LAST_LAYER_FOMO            2
#define EI_CLASSIFIER_LAST_LAYER_YOLOV5          3
#define EI_CLASSIFIER_LAST_LAYER_YOLOX           4
#define EI_CLASSIFIER_LAST_LAYER_YOLOV5_V5_DRPAI 5
#define EI_CLASSIFIER_LAST_LAYER_YOLOV7          6
#define EI_CLASSIFIER_LAST_LAYER_TAO_RETINANET   7
#define EI_CLASSIFIER_LAST_LAYER_TAO_SSD         8
#define EI_CLASSIFIER_LAST_LAYER_TAO_YOLOV3      9
#define EI_CLASSIFIER_LAST_LAYER_TAO_YOLOV4      10

#define EI_CLASSIFIER_IMAGE_SCALING_NONE         0
#define EI_CLASSIFIER_IMAGE_SCALING_0_255        1
#define EI_CLASSIFIER_IMAGE_SCALING_TORCH        2
#define EI_CLASSIFIER_IMAGE_SCALING_MIN1_1       3

#define EI_CLASSIFIER_TYPE_CLASSIFICATION        1
#define EI_CLASSIFIER_TYPE_OBJECT_DETECTION      2
#define EI_CLASSIFIER_TYPE_REGRESSION            3
#define EI_CLASSIFIER_MODE_CLASSIFICATION        EI_CLASSIFIER_TYPE_CLASSIFICATION
#define EI_CLASSIFIER_MODE_OBJECT_DETECTION      EI_CLASSIFIER_TYPE_OBJECT_DETECTION
#define EI_CLASSIFIER_MODE_REGRESSION            EI_CLASSIFIER_TYPE_REGRESSION
#endif /* EI_CLASSIFIER_NONE */

/* ── Compile-time model parameters (health model as primary) ───────────── */
/* Both models have 3 labels — this controls result struct sizing only.     */
#define EI_CLASSIFIER_LABEL_COUNT                3
#define EI_CLASSIFIER_HAS_VISUAL_ANOMALY         0
#define EI_CLASSIFIER_HR_ENABLED                 0
#define EI_CLASSIFIER_HAS_ANOMALY                EI_ANOMALY_TYPE_UNKNOWN
#define EI_CLASSIFIER_SENSOR                     EI_CLASSIFIER_SENSOR_CAMERA
#define EI_CLASSIFIER_DSP_AXES_INDEX_TYPE        uint8_t
#define EI_CLASSIFIER_INPUT_WIDTH                96
#define EI_CLASSIFIER_INPUT_HEIGHT               96
#define EI_CLASSIFIER_INPUT_FRAMES               1
#define EI_CLASSIFIER_RAW_SAMPLE_COUNT           9216
#define EI_CLASSIFIER_NN_INPUT_FRAME_SIZE        27648
#define EI_CLASSIFIER_DSP_INPUT_FRAME_SIZE       9216
#define EI_CLASSIFIER_OBJECT_DETECTION           0
#define EI_CLASSIFIER_OBJECT_DETECTION_LAST_LAYER EI_CLASSIFIER_LAST_LAYER_UNKNOWN
#define EI_CLASSIFIER_INFERENCING_ENGINE         EI_CLASSIFIER_TFLITE
#define EI_CLASSIFIER_COMPILED                   1
#define EI_CLASSIFIER_HAS_FFT_INFO               1
#define EI_CLASSIFIER_LOAD_IMAGE_SCALING         0
#define EI_CLASSIFIER_QUANTIZATION_ENABLED       1
#define EI_CLASSIFIER_TFLITE_INPUT_DATATYPE      EI_CLASSIFIER_DATATYPE_INT8
#define EI_CLASSIFIER_TFLITE_OUTPUT_DATATYPE     EI_CLASSIFIER_DATATYPE_INT8
#define EI_CLASSIFIER_HAS_DATA_NORMALIZATION     1
#define EI_CLASSIFIER_SLICES_PER_MODEL_WINDOW    4
#define EI_CLASSIFIER_SLICE_SIZE                 (EI_CLASSIFIER_RAW_SAMPLE_COUNT / EI_CLASSIFIER_SLICES_PER_MODEL_WINDOW)
#define EI_CLASSIFIER_INTERVAL_MS               1
#define EI_CLASSIFIER_FREQUENCY                 0

#endif /* _MG_STUB_MODEL_METADATA_H_ */
