; Standalone ESP8266 test project: Wi-Fi + LCD + buzzer + DHT22

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed=9600


lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
