import os
import json
import asyncio
import secrets
import smtplib
import time
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from passlib.context import CryptContext

from fastapi import FastAPI, Depends, HTTPException, WebSocket, WebSocketDisconnect, Form, Header, BackgroundTasks, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from typing import Optional
from sqlalchemy.orm import Session
from sqlalchemy import case, text, inspect
from jose import jwt, JWTError

from . import models, schemas, logic, database
from .database import engine, get_db

# Create database tables
models.Base.metadata.create_all(bind=engine)


def ensure_user_settings_columns():
    """Backfill user preference columns for existing databases without migrations."""
    inspector = inspect(engine)
    user_columns = {column["name"] for column in inspector.get_columns("users")}

    with engine.begin() as connection:
        if "notification_emails_enabled" not in user_columns:
            connection.execute(
                text("ALTER TABLE users ADD COLUMN notification_emails_enabled BOOLEAN DEFAULT TRUE")
            )
            connection.execute(
                text("UPDATE users SET notification_emails_enabled = TRUE WHERE notification_emails_enabled IS NULL")
            )

        if "disease_confidence_threshold" not in user_columns:
            connection.execute(
                text("ALTER TABLE users ADD COLUMN disease_confidence_threshold INTEGER DEFAULT 70")
            )
            connection.execute(
                text("UPDATE users SET disease_confidence_threshold = 70 WHERE disease_confidence_threshold IS NULL")
            )


ensure_user_settings_columns()

APP_STARTED_AT = time.time()
REQUEST_SLOW_MS = float(os.getenv("REQUEST_SLOW_MS", "800"))

def send_alert_email(email: str, subject: str, message: str):
    """
    Send an alert email via SMTP when configured.
    """
    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_username = os.getenv("SMTP_USERNAME")
    smtp_password = os.getenv("SMTP_PASSWORD")
    smtp_from = os.getenv("SMTP_FROM_EMAIL") or smtp_username
    smtp_use_tls = os.getenv("SMTP_USE_TLS", "true").lower() != "false"

    if not smtp_host or not smtp_from:
        print(f"\n[EMAIL SKIPPED]\nSMTP is not configured. Intended recipient: {email}\nSubject: {subject}\n")
        return

    email_message = EmailMessage()
    email_message["Subject"] = subject
    email_message["From"] = smtp_from
    email_message["To"] = email
    email_message.set_content(message)
    email_message.add_alternative(
        f"""
        <html>
          <body style="margin:0;padding:24px;background:#f6f8fb;font-family:Segoe UI,Arial,sans-serif;color:#172033;">
            <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
              <tr>
                <td align="center">
                  <table role="presentation" width="100%" style="max-width:640px;background:#ffffff;border-radius:18px;overflow:hidden;border:1px solid #d8e1ef;">
                    <tr>
                      <td style="padding:24px 28px;background:linear-gradient(135deg,#0f7b6c,#1e5aa8);color:#ffffff;">
                        <div style="font-size:12px;letter-spacing:1.5px;text-transform:uppercase;opacity:0.9;">Intelligent Mango Health Monitoring</div>
                        <h1 style="margin:10px 0 0;font-size:24px;line-height:1.2;">{subject}</h1>
                      </td>
                    </tr>
                    <tr>
                      <td style="padding:28px;">
                        <p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#344054;">{message}</p>
                        <div style="margin-top:20px;padding:16px 18px;background:#f3f7fc;border-left:4px solid #1e5aa8;border-radius:12px;">
                          <div style="font-size:13px;color:#52607a;line-height:1.6;">
                            This alert was generated by your mango monitoring system based on recent device data.
                          </div>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td style="padding:18px 28px;background:#f8fafc;font-size:12px;color:#667085;">
                        Review your dashboard for the latest disease status, forecast, and recommendations.
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
          </body>
        </html>
        """,
        subtype="html",
    )

    with smtplib.SMTP(smtp_host, smtp_port, timeout=20) as server:
        server.ehlo()
        if smtp_use_tls:
            server.starttls()
            server.ehlo()
        if smtp_username and smtp_password:
            server.login(smtp_username, smtp_password)
        server.send_message(email_message)

app = FastAPI(title="Intelligent Plant Health Monitoring API")

# Password hashing
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

# JWT config
SECRET_KEY = os.getenv("SECRET_KEY", "mangoguard-plant-health-secret-key-change-in-production")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24  # 24 hours

# Default user credentials (for backward compatibility)
DEFAULT_USERNAME = os.getenv("ADMIN_USERNAME", "admin")
DEFAULT_PASSWORD = os.getenv("ADMIN_PASSWORD", "admin")

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Adjust in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Active WebSocket connections ---
connected_clients: list[dict] = []


def format_duration_ms(start_time: float) -> float:
    return round((time.perf_counter() - start_time) * 1000, 2)


def log_request_timing(method: str, path: str, status_code: int, duration_ms: float, request_id: str):
    speed = "slow" if duration_ms >= REQUEST_SLOW_MS else "ok"
    print(
        f"[request_timing] id={request_id} method={method} path={path} "
        f"status={status_code} duration_ms={duration_ms} speed={speed}"
    )


@app.middleware("http")
async def add_request_timing(request: Request, call_next):
    start_time = time.perf_counter()
    request_id = secrets.token_hex(4)

    try:
        response = await call_next(request)
    except Exception as exc:
        duration_ms = format_duration_ms(start_time)
        log_request_timing(request.method, request.url.path, 500, duration_ms, request_id)
        raise exc

    duration_ms = format_duration_ms(start_time)
    response.headers["X-Request-ID"] = request_id
    response.headers["X-Response-Time-Ms"] = str(duration_ms)
    log_request_timing(request.method, request.url.path, response.status_code, duration_ms, request_id)
    return response


def scoped_device_id(device: models.Device) -> str:
    """Build a stable internal device id used for user-scoped data storage."""
    return f"device:{device.id}"


def get_user_scoped_device_ids(db: Session, user_id: int) -> list[str]:
    """Return all internal device ids that belong to a user."""
    devices = db.query(models.Device).filter(models.Device.user_id == user_id).all()
    return [scoped_device_id(d) for d in devices]


def decode_user_from_token(token: str, db: Session) -> Optional[models.User]:
    """Decode JWT token and return the matching user if valid."""
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username = payload.get("sub")
        if not username:
            return None
        return db.query(models.User).filter(models.User.username == username).first()
    except JWTError:
        return None


async def broadcast_to_clients(message: dict, owner_id: Optional[int] = None):
    """Send a message only to the owner's active WebSocket clients."""
    dead = []
    for client in connected_clients:
        ws = client["ws"]
        ws_owner_id = client["user_id"]

        if owner_id is not None and ws_owner_id != owner_id:
            continue

        try:
            await ws.send_json(message)
        except Exception:
            dead.append(client)

    for client in dead:
        if client in connected_clients:
            connected_clients.remove(client)


def build_dashboard_payload(sensor, inference, db: Session) -> dict:
    """Build the JSON payload the frontend Dashboard expects."""
    risk = logic.evaluate_risk(inference.disease_type, sensor.temperature, sensor.humidity)
    forecast_alert = logic.get_forecast_alert(sensor.temperature, sensor.humidity)

    # Compute a simple stability score (0-100) from confidence + env risk
    stability = round(inference.confidence_score * 100)
    if risk["risk_level"] == "HIGH RISK":
        stability = max(0, stability - 30)
    elif risk["risk_level"] == "MEDIUM RISK":
        stability = max(0, stability - 15)

    # Map risk level to health status
    health_map = {"LOW RISK": "OPTIMAL", "MEDIUM RISK": "WARNING", "HIGH RISK": "CRITICAL"}
    health = health_map.get(risk["risk_level"], "OPTIMAL")

    recommendations = []
    if risk["recommendation"]:
        recommendations.append({
            "title": risk["risk_level"],
            "desc": risk["recommendation"]
        })
    if forecast_alert and "High Risk" in forecast_alert:
        recommendations.append({
            "title": "Forecast Alert",
            "desc": forecast_alert
        })
    if inference.disease_type != "Healthy":
        recommendations.append({
            "title": f"{inference.disease_type} Detected",
            "desc": logic.get_recommendation(inference.disease_type)
        })

    return {
        "temperature": sensor.temperature,
        "humidity": sensor.humidity,
        "moisture": round(sensor.humidity * 0.85, 1),  # derived estimate
        "health": health,
        "stability": stability,
        "disease_type": inference.disease_type,
        "confidence_score": inference.confidence_score,
        "risk_level": risk["risk_level"],
        "recommendations": recommendations,
        "timestamp": inference.timestamp.isoformat() if inference.timestamp else None,
    }


def build_analysis_summary(
    detections: list[models.InferenceResult],
    sensors: list[models.SensorData],
    recommendations: list[models.Recommendation],
    forecasts: list[models.ForecastData],
) -> dict:
    localized_recommendations = [
        {
            "title": r.title,
            "title_am": r.title_am,
        }
        for r in recommendations
        if r.title or r.title_am
    ]

    if not detections:
        return {
            "total_scans": 0,
            "healthy_rate": 0,
            "top_disease_label": None,
            "disease_count": 0,
            "healthy_count": 0,
            "healthy_temp_avg": None,
            "healthy_humidity_avg": None,
            "diseased_temp_avg": None,
            "diseased_humidity_avg": None,
            "risk_level": "LOW",
            "risk_score": 0,
            "disease_rate": 0,
            "average_confidence": 0,
            "recommendation_count": len(recommendations),
            "latest_recommendation": localized_recommendations[0] if localized_recommendations else None,
            "high_risk_days": 0,
            "stable_days": 0,
            "sensor_sample_count": len(sensors),
            "confidence_trend": [],
            "temperature_trend": [],
            "disease_breakdown": [],
            "forecast_risk_trend": [],
            "top_recommendations": localized_recommendations[:3],
        }

    disease_frequency = {}
    healthy_count = 0
    disease_count = 0
    healthy_temp_total = 0
    healthy_humidity_total = 0
    healthy_with_env_count = 0
    diseased_temp_total = 0
    diseased_humidity_total = 0
    diseased_with_env_count = 0
    confidence_total = 0

    for entry in detections:
        disease_type = entry.disease_type or "Unknown"
        is_healthy = disease_type.lower() == "healthy"
        has_temperature = isinstance(getattr(entry, "temperature", None), (int, float))
        has_humidity = isinstance(getattr(entry, "humidity", None), (int, float))

        confidence_total += float(entry.confidence_score or 0)

        if is_healthy:
            healthy_count += 1
            if has_temperature and has_humidity:
                healthy_temp_total += entry.temperature
                healthy_humidity_total += entry.humidity
                healthy_with_env_count += 1
            continue

        disease_count += 1
        disease_frequency[disease_type] = (disease_frequency.get(disease_type, 0) + 1)
        if has_temperature and has_humidity:
            diseased_temp_total += entry.temperature
            diseased_humidity_total += entry.humidity
            diseased_with_env_count += 1

    top_disease_label = None
    max_count = 0
    for disease, count in disease_frequency.items():
        if count > max_count:
            max_count = count
            top_disease_label = disease

    healthy_rate = (healthy_count / len(detections)) * 100
    recent_window = detections[: min(25, len(detections))]
    recent_diseased = len([d for d in recent_window if (d.disease_type or "").lower() != "healthy"])
    disease_rate = (recent_diseased / len(recent_window)) * 100 if recent_window else 0
    average_confidence = (confidence_total / len(detections)) * 100 if detections else 0

    risk_score = round(disease_rate * 0.7 + average_confidence * 0.3)
    risk_level = "LOW"
    if risk_score >= 65:
        risk_level = "HIGH"
    elif risk_score >= 40:
        risk_level = "MEDIUM"

    high_risk_days = len([f for f in forecasts if "HIGH" in (f.risk_level or "").upper()])
    stable_days = max(0, len(forecasts) - high_risk_days)

    confidence_trend = [
        max(0, min(100, round((d.confidence_score or 0) * 100)))
        for d in reversed(detections[:12])
    ]

    temperature_values = [
        s.temperature for s in sensors[-12:]
        if isinstance(s.temperature, (int, float))
    ]
    if temperature_values:
        min_temp = min(temperature_values)
        max_temp = max(temperature_values)
        temp_range = max(1, max_temp - min_temp)
        temperature_trend = [round(((value - min_temp) / temp_range) * 100) for value in temperature_values]
    else:
        temperature_trend = []

    total_diseased = max(1, disease_count)
    disease_breakdown = [
        {
            "name": name,
            "count": count,
            "pct": round((count / total_diseased) * 100),
        }
        for name, count in sorted(disease_frequency.items(), key=lambda item: item[1], reverse=True)[:4]
    ]

    forecast_risk_trend = []
    for forecast in forecasts:
        risk = (forecast.risk_level or "").upper()
        if "HIGH" in risk:
            forecast_risk_trend.append(90)
        elif "MEDIUM" in risk:
            forecast_risk_trend.append(60)
        else:
            forecast_risk_trend.append(30)

    return {
        "total_scans": len(detections),
        "healthy_rate": healthy_rate,
        "top_disease_label": top_disease_label,
        "disease_count": disease_count,
        "healthy_count": healthy_count,
        "healthy_temp_avg": (healthy_temp_total / healthy_with_env_count) if healthy_with_env_count else None,
        "healthy_humidity_avg": (healthy_humidity_total / healthy_with_env_count) if healthy_with_env_count else None,
        "diseased_temp_avg": (diseased_temp_total / diseased_with_env_count) if diseased_with_env_count else None,
        "diseased_humidity_avg": (diseased_humidity_total / diseased_with_env_count) if diseased_with_env_count else None,
        "risk_level": risk_level,
        "risk_score": risk_score,
        "disease_rate": disease_rate,
        "average_confidence": average_confidence,
        "recommendation_count": len(recommendations),
        "latest_recommendation": localized_recommendations[0] if localized_recommendations else None,
        "high_risk_days": high_risk_days,
        "stable_days": stable_days,
        "sensor_sample_count": len(sensors),
        "confidence_trend": confidence_trend,
        "temperature_trend": temperature_trend,
        "disease_breakdown": disease_breakdown,
        "forecast_risk_trend": forecast_risk_trend,
        "top_recommendations": localized_recommendations[:3],
    }


# ------------------------------------------------------------------
# Auth endpoint
# ------------------------------------------------------------------

def verify_password(plain_password, hashed_password):
    return pwd_context.verify(plain_password, hashed_password)

def get_password_hash(password):
    return pwd_context.hash(password)

def get_current_user(authorization: str = Header(...), db: Session = Depends(get_db)):
    """Extract user from JWT Bearer token."""
    try:
        token = authorization.replace("Bearer ", "")
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username = payload.get("sub")
        if not username:
            raise HTTPException(status_code=401, detail="Invalid token")
    except JWTError:
        raise HTTPException(status_code=401, detail="Invalid token")
    user = db.query(models.User).filter(models.User.username == username).first()
    if not user:
        raise HTTPException(status_code=401, detail="User not found")
    return user

@app.post("/register")
async def register(
    username: str = Form(...),
    password: str = Form(...),
    email: str = Form(...),
    db: Session = Depends(get_db)
):
    """Register a new user with email."""
    if not username or not password or not email:
        raise HTTPException(status_code=400, detail="Username, password, and email are required")

    if len(password) < 6:
        raise HTTPException(status_code=400, detail="Password must be at least 6 characters")

    # Check if user already exists
    existing_user = db.query(models.User).filter(models.User.username == username).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Username already exists")

    existing_email = db.query(models.User).filter(models.User.email == email).first()
    if existing_email:
        raise HTTPException(status_code=400, detail="Email already registered")

    # Create new user
    hashed_password = get_password_hash(password)
    new_user = models.User(username=username, email=email, password=hashed_password)
    db.add(new_user)
    db.commit()
    db.refresh(new_user)

    # Generate token
    expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    token = jwt.encode({"sub": username, "exp": expire}, SECRET_KEY, algorithm=ALGORITHM)
    return {"access_token": token, "token_type": "bearer"}

@app.post("/login")
async def login(username: str = Form(...), password: str = Form(...), db: Session = Depends(get_db)):
    """Login user with username and password."""
    # Try to find user in database
    user = db.query(models.User).filter(models.User.username == username).first()

    if user and verify_password(password, user.password):
        expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
        token = jwt.encode({"sub": username, "exp": expire}, SECRET_KEY, algorithm=ALGORITHM)
        return {"access_token": token, "token_type": "bearer"}

    # Fallback to default credentials for backward compatibility
    if username == DEFAULT_USERNAME and password == DEFAULT_PASSWORD:
        expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
        token = jwt.encode({"sub": username, "exp": expire}, SECRET_KEY, algorithm=ALGORITHM)
        return {"access_token": token, "token_type": "bearer"}

    raise HTTPException(status_code=401, detail="Invalid credentials")


# ------------------------------------------------------------------
# Profile endpoints
# ------------------------------------------------------------------

@app.get("/me", response_model=schemas.UserProfileOut)
def get_current_user_profile(user: models.User = Depends(get_current_user)):
    """Get the current user's profile information."""
    return user

@app.put("/profile", response_model=schemas.UserProfileOut)
def update_profile(
    payload: schemas.UserProfileUpdate,
    db: Session = Depends(get_db),
    user: models.User = Depends(get_current_user)
):
    """Update the current user's profile."""
    # Check email uniqueness if changing
    if payload.email and payload.email != user.email:
        existing = db.query(models.User).filter(
            models.User.email == payload.email,
            models.User.id != user.id
        ).first()
        if existing:
            raise HTTPException(status_code=400, detail="Email already in use")

    # Update fields
    if payload.display_name is not None:
        user.display_name = payload.display_name
    if payload.email is not None:
        user.email = payload.email
    if payload.avatar_url is not None:
        user.avatar_url = payload.avatar_url
    if payload.notification_emails_enabled is not None:
        user.notification_emails_enabled = payload.notification_emails_enabled
    if payload.disease_confidence_threshold is not None:
        threshold = max(50, min(95, int(payload.disease_confidence_threshold)))
        user.disease_confidence_threshold = threshold

    db.commit()
    db.refresh(user)
    return user

@app.put("/profile/password")
def change_password(
    payload: schemas.PasswordChangeRequest,
    db: Session = Depends(get_db),
    user: models.User = Depends(get_current_user)
):
    """Change the current user's password."""
    # Verify current password
    if not verify_password(payload.current_password, user.password):
        raise HTTPException(status_code=400, detail="Current password is incorrect")

    # Validate new password
    if len(payload.new_password) < 6:
        raise HTTPException(status_code=400, detail="New password must be at least 6 characters")

    # Update password
    user.password = get_password_hash(payload.new_password)
    db.commit()

    return {"status": "success", "message": "Password updated successfully"}


# ------------------------------------------------------------------
# WebSocket endpoint  —  streams latest data to the frontend
# ------------------------------------------------------------------

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket, token: str = None):
    if not token:
        await websocket.close(code=1008)
        return

    db = database.SessionLocal()
    user = decode_user_from_token(token, db)
    if not user:
        db.close()
        await websocket.close(code=1008)
        return

    user_device_ids = get_user_scoped_device_ids(db, user.id)

    await websocket.accept()
    client_entry = {"ws": websocket, "user_id": user.id}
    connected_clients.append(client_entry)
    try:
        # Send current state immediately on connect
        try:
            inference_query = db.query(models.InferenceResult)
            if user_device_ids:
                inference_query = inference_query.filter(models.InferenceResult.device_id.in_(user_device_ids))
            inference = inference_query.order_by(models.InferenceResult.timestamp.desc()).first()
            if inference:
                # Get sensor data at the time of detection (to match dashboard/logs)
                sensor = db.query(models.SensorData).filter(
                    models.SensorData.timestamp <= inference.timestamp,
                    models.SensorData.device_id == inference.device_id
                ).order_by(models.SensorData.timestamp.desc()).first()
                if not sensor:
                    sensor_query = db.query(models.SensorData)
                    if user_device_ids:
                        sensor_query = sensor_query.filter(models.SensorData.device_id.in_(user_device_ids))
                    sensor = sensor_query.order_by(models.SensorData.timestamp.asc()).first()
                if sensor:
                    payload = build_dashboard_payload(sensor, inference, db)
                    await websocket.send_json(payload)
        finally:
            db.close()

        # Keep connection alive and listen for any client messages
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        pass
    finally:
        if client_entry in connected_clients:
            connected_clients.remove(client_entry)


# ------------------------------------------------------------------
# Existing endpoints
# ------------------------------------------------------------------

@app.get("/")
def read_root():
    return {"message": "Welcome to the Intelligent Plant Health Monitoring API"}


@app.get("/health")
def health_check():
    """Lightweight health and database connectivity probe."""
    db_start = time.perf_counter()
    db_ok = False
    db_error = None

    try:
        with engine.connect() as connection:
            connection.execute(text("SELECT 1"))
        db_ok = True
    except Exception as exc:
        db_error = str(exc)

    db_duration_ms = format_duration_ms(db_start)
    uptime_seconds = round(time.time() - APP_STARTED_AT, 2)
    overall_status = "ok" if db_ok else "degraded"

    payload = {
        "status": overall_status,
        "service": "backend",
        "uptime_seconds": uptime_seconds,
        "database": {
            "ok": db_ok,
            "duration_ms": db_duration_ms,
        },
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

    if db_error:
        payload["database"]["error"] = db_error

    if db_ok:
        return payload

    return JSONResponse(status_code=503, content=payload)


@app.post("/upload", response_model=dict)
async def upload_data(
    payload: schemas.UploadPayload,
    db: Session = Depends(get_db),
    x_device_key: Optional[str] = Header(None)
):
    if not x_device_key:
        raise HTTPException(status_code=401, detail="X-Device-Key header is required")

    device = db.query(models.Device).filter(models.Device.api_key == x_device_key).first()
    if not device:
        raise HTTPException(status_code=401, detail="Invalid device API key")

    owner_id = device.user_id
    device.last_seen = datetime.utcnow()
    db.commit()
    internal_device_id = scoped_device_id(device)

    # Create Sensor Data record
    new_sensor_data = models.SensorData(
        device_id=internal_device_id,
        temperature=payload.temperature,
        humidity=payload.humidity
    )
    db.add(new_sensor_data)

    # Create Inference Result record
    new_inference = models.InferenceResult(
        device_id=internal_device_id,
        disease_type=payload.disease_type,
        confidence_score=payload.confidence_score
    )
    db.add(new_inference)

    db.commit()
    db.refresh(new_sensor_data)
    db.refresh(new_inference)

    # Evaluate risk
    risk = logic.evaluate_risk(payload.disease_type, payload.temperature, payload.humidity)
    forecast_alert = logic.get_forecast_alert(payload.temperature, payload.humidity)

    # Broadcast only to the owning user's dashboard clients
    dashboard_payload = build_dashboard_payload(new_sensor_data, new_inference, db)
    await broadcast_to_clients(dashboard_payload, owner_id=owner_id)

    return {
        "status": "success",
        "data_id": new_sensor_data.id,
        "inference_id": new_inference.id,
        "risk_level": risk["risk_level"],
        "recommendation": risk["recommendation"],
        "forecast_alert": forecast_alert
    }


@app.get("/history", response_model=schemas.HistoricalData)
def get_history(
    db: Session = Depends(get_db),
    limit: int = 100,
    user: models.User = Depends(get_current_user)
):
    user_device_ids = get_user_scoped_device_ids(db, user.id)
    if not user_device_ids:
        return {"sensor_data": [], "inference_results": []}

    sensor_data = db.query(models.SensorData).filter(
        models.SensorData.device_id.in_(user_device_ids)
    ).order_by(models.SensorData.timestamp.desc()).limit(limit).all()

    inference_results = db.query(models.InferenceResult).filter(
        models.InferenceResult.device_id.in_(user_device_ids)
    ).order_by(models.InferenceResult.timestamp.desc()).limit(limit).all()

    return {
        "sensor_data": sensor_data,
        "inference_results": inference_results
    }


# ------------------------------------------------------------------
# NEW MangaGuard API Endpoints
# ------------------------------------------------------------------

@app.get("/sensors/latest", response_model=schemas.SensorLatest)
def get_sensors_latest(db: Session = Depends(get_db), user: models.User = Depends(get_current_user)):
    """Get the latest sensor reading (temperature and humidity)."""
    user_device_ids = get_user_scoped_device_ids(db, user.id)
    if not user_device_ids:
        raise HTTPException(status_code=404, detail="No sensor data available")

    sensor = db.query(models.SensorData).filter(
        models.SensorData.device_id.in_(user_device_ids)
    ).order_by(models.SensorData.timestamp.desc()).first()
    if not sensor:
        raise HTTPException(status_code=404, detail="No sensor data available")
    return {
        "temperature": sensor.temperature,
        "humidity": sensor.humidity,
        "timestamp": sensor.timestamp
    }


@app.get("/sensors/history")
def get_sensors_history(
    range: str = "24h",
    db: Session = Depends(get_db),
    user: models.User = Depends(get_current_user)
):
    """
    Get sensor history for a specified time range.
    range: '24h', '7d', or '30d'
    """
    now = datetime.now(timezone.utc)

    if range == "24h":
        start_time = now - timedelta(hours=24)
    elif range == "7d":
        start_time = now - timedelta(days=7)
    elif range == "30d":
        start_time = now - timedelta(days=30)
    else:
        start_time = now - timedelta(hours=24)  # default to 24h

    user_device_ids = get_user_scoped_device_ids(db, user.id)
    if not user_device_ids:
        return {"range": range, "data": []}

    data = db.query(models.SensorData).filter(
        models.SensorData.timestamp >= start_time,
        models.SensorData.device_id.in_(user_device_ids)
    ).order_by(models.SensorData.timestamp.asc()).all()

    return {
        "range": range,
        "data": [
            {
                "temperature": d.temperature,
                "humidity": d.humidity,
                "timestamp": d.timestamp
            } for d in data
        ]
    }


@app.get("/detection/latest")
def get_detection_latest(db: Session = Depends(get_db), user: models.User = Depends(get_current_user)):
    """Get the absolute latest disease detection result with matching sensor data."""
    user_device_ids = get_user_scoped_device_ids(db, user.id)
    if not user_device_ids:
        raise HTTPException(status_code=404, detail="No detection data available")

    detection = db.query(models.InferenceResult).order_by(
        models.InferenceResult.timestamp.desc()
    ).filter(models.InferenceResult.device_id.in_(user_device_ids)).first()

    if not detection:
        raise HTTPException(status_code=404, detail="No detection data available")

    # Get sensor data at the time of detection (same as /detection/history does)
    sensor = db.query(models.SensorData).filter(
        models.SensorData.timestamp <= detection.timestamp,
        models.SensorData.device_id == detection.device_id
    ).order_by(models.SensorData.timestamp.desc()).first()

    # Fallback to nearest sensor if none before
    if not sensor:
        sensor = db.query(models.SensorData).filter(
            models.SensorData.device_id.in_(user_device_ids)
        ).order_by(models.SensorData.timestamp.asc()).first()

    return {
        "disease_type": detection.disease_type,
        "confidence_score": detection.confidence_score,
        "timestamp": detection.timestamp,
        "temperature": sensor.temperature if sensor else None,
        "humidity": sensor.humidity if sensor else None
    }


@app.get("/detection/history")
def get_detection_history(
    page: int = 1,
    limit: int = 10,
    disease_first: bool = False,
    db: Session = Depends(get_db),
    user: models.User = Depends(get_current_user),
):
    """
    Get paginated detection history with sensor readings at time of detection.
    """
    skip = (page - 1) * limit

    user_device_ids = get_user_scoped_device_ids(db, user.id)
    if not user_device_ids:
        return {
            "page": page,
            "limit": limit,
            "total": 0,
            "total_pages": 0,
            "data": []
        }

    query = db.query(models.InferenceResult).filter(
        models.InferenceResult.device_id.in_(user_device_ids)
    )

    if disease_first:
        # Prioritize non-healthy detections, then newest timestamp.
        query = query.order_by(
            case((models.InferenceResult.disease_type == "Healthy", 1), else_=0),
            models.InferenceResult.timestamp.desc(),
        )
    else:
        query = query.order_by(models.InferenceResult.timestamp.desc())

    detections = query.offset(skip).limit(limit).all()

    total = db.query(models.InferenceResult).filter(
        models.InferenceResult.device_id.in_(user_device_ids)
    ).count()

    result = []
    for detection in detections:
        # Find the most recent sensor data at or before detection time
        sensor = db.query(models.SensorData).filter(
            models.SensorData.timestamp <= detection.timestamp,
            models.SensorData.device_id == detection.device_id
        ).order_by(models.SensorData.timestamp.desc()).first()

        # Fallback: get nearest sensor reading if none before
        if not sensor:
            sensor = db.query(models.SensorData).filter(
                models.SensorData.device_id.in_(user_device_ids)
            ).order_by(models.SensorData.timestamp.asc()).first()

        result.append({
            "id": detection.id,
            "disease_type": detection.disease_type,
            "confidence_score": detection.confidence_score,
            "timestamp": detection.timestamp,
            "temperature": sensor.temperature if sensor else None,
            "humidity": sensor.humidity if sensor else None
        })

    return {
        "page": page,
        "limit": limit,
        "total": total,
        "total_pages": (total + limit - 1) // limit,
        "data": result
    }


@app.get("/forecast/latest")
def get_forecast_latest(db: Session = Depends(get_db), user: models.User = Depends(get_current_user)):
    """
    Get the latest 5-day forecast with available context.
    """
    user_device_ids = get_user_scoped_device_ids(db, user.id)
    if not user_device_ids:
        raise HTTPException(status_code=404, detail="No forecast data available")

    # Get the most recent forecast context
    context = db.query(models.ForecastContext).filter(
        models.ForecastContext.device_id.in_(user_device_ids)
    ).order_by(models.ForecastContext.timestamp.desc()).first()

    if not context:
        raise HTTPException(status_code=404, detail="No forecast data available")

    # Get forecast data for this context
    forecasts = db.query(models.ForecastData).filter(
        models.ForecastData.context_id == context.id
    ).order_by(models.ForecastData.day_index.asc()).all()

    return {
        "context": {
            "timestamp": context.timestamp
        },
        "days": [
            {
                "day": (f.day_index + 1),
                "risk_level": f.risk_level,
                "date": f.forecast_date
            } for f in forecasts
        ],
        "created_at": context.timestamp
    }


@app.post("/forecast/context")
def post_forecast_context(
    payload: schemas.ForecastContextPayload,
    db: Session = Depends(get_db),
    x_device_key: Optional[str] = Header(None)
):
    """
    Accept forecast context from ESP32.
    """
    if not x_device_key:
        raise HTTPException(status_code=401, detail="X-Device-Key header is required")

    device = db.query(models.Device).filter(models.Device.api_key == x_device_key).first()
    if not device:
        raise HTTPException(status_code=401, detail="Invalid device API key")

    internal_device_id = scoped_device_id(device)
    new_context = models.ForecastContext(device_id=internal_device_id)
    db.add(new_context)
    db.commit()
    db.refresh(new_context)

    return {
        "status": "success",
        "context_id": new_context.id,
        "message": "Forecast context recorded"
    }


@app.get("/recommendations/latest")
def get_recommendations_latest(
    db: Session = Depends(get_db),
    limit: int = 5,
    user: models.User = Depends(get_current_user)
):
    """
    Get the latest recommendations.
    """
    user_device_ids = get_user_scoped_device_ids(db, user.id)
    if not user_device_ids:
        return {"data": []}

    recommendations = db.query(models.Recommendation).filter(
        models.Recommendation.device_id.in_(user_device_ids)
    ).order_by(
        models.Recommendation.timestamp.desc()
    ).limit(limit).all()

    return {
        "data": [
            {
                "id": r.id,
                "title": r.title,
                "description": r.description,
                "title_am": r.title_am,
                "description_am": r.description_am,
                "timestamp": r.timestamp
            } for r in recommendations
        ]
    }


@app.get("/analysis/summary")
def get_analysis_summary(db: Session = Depends(get_db), user: models.User = Depends(get_current_user)):
    """Get a compact analysis summary for the Analysis page in a single request."""
    user_device_ids = get_user_scoped_device_ids(db, user.id)
    if not user_device_ids:
        return build_analysis_summary([], [], [], [])

    detections = db.query(models.InferenceResult).filter(
        models.InferenceResult.device_id.in_(user_device_ids)
    ).order_by(models.InferenceResult.timestamp.desc()).limit(200).all()

    enriched_detections = []
    for detection in detections:
        sensor = db.query(models.SensorData).filter(
            models.SensorData.timestamp <= detection.timestamp,
            models.SensorData.device_id == detection.device_id
        ).order_by(models.SensorData.timestamp.desc()).first()

        if not sensor:
            sensor = db.query(models.SensorData).filter(
                models.SensorData.device_id.in_(user_device_ids)
            ).order_by(models.SensorData.timestamp.asc()).first()

        detection.temperature = sensor.temperature if sensor else None
        detection.humidity = sensor.humidity if sensor else None
        enriched_detections.append(detection)

    sensors = db.query(models.SensorData).filter(
        models.SensorData.device_id.in_(user_device_ids)
    ).order_by(models.SensorData.timestamp.asc()).all()

    recommendations = db.query(models.Recommendation).filter(
        models.Recommendation.device_id.in_(user_device_ids)
    ).order_by(models.Recommendation.timestamp.desc()).limit(50).all()

    latest_context = db.query(models.ForecastContext).filter(
        models.ForecastContext.device_id.in_(user_device_ids)
    ).order_by(models.ForecastContext.timestamp.desc()).first()

    forecasts = []
    if latest_context:
        forecasts = db.query(models.ForecastData).filter(
            models.ForecastData.context_id == latest_context.id
        ).order_by(models.ForecastData.day_index.asc()).all()

    return build_analysis_summary(enriched_detections, sensors, recommendations, forecasts)


@app.post("/data/ingest")
async def data_ingest(
    payload: schemas.DataIngestPayload,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    x_device_key: Optional[str] = Header(None)
):
    """
    Combined endpoint for ESP32 to submit all data in one call.
    Authenticates via X-Device-Key header and stores data under the
    owner's internal device scope so users only see their own device data.
    """
    if not x_device_key:
        raise HTTPException(status_code=401, detail="X-Device-Key header is required")

    device = db.query(models.Device).filter(models.Device.api_key == x_device_key).first()
    if not device:
        raise HTTPException(status_code=401, detail="Invalid device API key")

    owner_id = device.user_id
    device.last_seen = datetime.utcnow()
    db.commit()
    internal_device_id = scoped_device_id(device)

    try:
        server_now = datetime.now(timezone.utc)

        # 1. Store sensor data
        new_sensor = models.SensorData(
            device_id=internal_device_id,
            temperature=payload.temperature,
            humidity=payload.humidity,
            timestamp=server_now
        )
        db.add(new_sensor)

        # 2. Store detection result
        new_detection = models.InferenceResult(
            device_id=internal_device_id,
            disease_type=payload.disease_type,
            confidence_score=payload.confidence_score,
            timestamp=server_now
        )
        db.add(new_detection)

        # 3. Store forecast context
        new_context = models.ForecastContext(
            device_id=internal_device_id,
            timestamp=server_now
        )
        db.add(new_context)

        db.commit()
        db.refresh(new_sensor)
        db.refresh(new_detection)
        db.refresh(new_context)

        # 4. Store recommendations if provided
        if payload.recommendations:
            for rec in payload.recommendations:
                new_rec = models.Recommendation(
                    device_id=internal_device_id,
                    title=rec.title,
                    description=rec.description,
                    title_am=rec.title_am,
                    description_am=rec.description_am,
                    timestamp=server_now
                )
                db.add(new_rec)
            db.commit()

        # 5. Store forecast data if provided
        if payload.forecast:
            for i, day_forecast in enumerate(payload.forecast):
                forecast_date = server_now + timedelta(days=i + 1)
                new_forecast = models.ForecastData(
                    device_id=internal_device_id,
                    day_index=i,
                    risk_level=day_forecast.get("risk_level", "Stable"),
                    forecast_date=forecast_date,
                    context_id=new_context.id
                )
                db.add(new_forecast)
            db.commit()

        # Build response payload and broadcast to WebSocket clients
        dashboard_payload = {
            "temperature": payload.temperature,
            "humidity": payload.humidity,
            "disease_type": payload.disease_type,
            "confidence_score": payload.confidence_score,
            "timestamp": new_detection.timestamp.isoformat() if new_detection.timestamp else datetime.now(timezone.utc).isoformat()
        }

        await broadcast_to_clients(dashboard_payload, owner_id=owner_id)

        # 6. Auto-generate notifications only for the device owner
        users = [db.query(models.User).filter(models.User.id == owner_id).first()]
        users = [u for u in users if u]
        for user in users:
            confidence_threshold = max(50, min(95, int(user.disease_confidence_threshold or 70))) / 100.0
            email_enabled = bool(user.notification_emails_enabled)

            # Disease alert - only if confidence exceeds the user's threshold
            if payload.disease_type != "Healthy" and payload.confidence_score >= confidence_threshold:
                title = f"{payload.disease_type} Detected"
                message = f"{payload.disease_type} detected with {payload.confidence_score*100:.1f}% confidence. Check your mango plants."
                db.add(models.Notification(user_id=user.id, title=title, message=message, type="disease_alert"))
                if user.email and email_enabled:
                    background_tasks.add_task(send_alert_email, user.email, title, message)
                    
            # Forecast alerts for high-risk predictions
            if payload.forecast:
                for i, day_forecast in enumerate(payload.forecast):
                    risk_level = day_forecast.get("risk_level", "Stable")
                    if "High" in risk_level:
                        # Determine disease type from risk level
                        if "Anthracnose" in risk_level:
                            risk_name = "Anthracnose"
                        elif "Mildew" in risk_level:
                            risk_name = "Powdery Mildew"
                        else:
                            risk_name = "Disease"
                        day_num = i + 1
                        title = f"Day {day_num} Forecast: High {risk_name} Risk"
                        message = f"Forecast predicts high {risk_name.lower()} risk in {day_num} day(s). Consider preventive measures."
                        
                        db.add(models.Notification(user_id=user.id, title=title, message=message, type="forecast_alert"))
                        if user.email and email_enabled:
                            background_tasks.add_task(send_alert_email, user.email, title, message)
                            
        db.commit()

        return {
            "status": "success",
            "sensor_id": new_sensor.id,
            "detection_id": new_detection.id,
            "context_id": new_context.id,
            "message": "Data ingested successfully"
        }

    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=400, detail=str(e))


# ------------------------------------------------------------------
# Notification endpoints
# ------------------------------------------------------------------

@app.get("/notifications")
def get_notifications(db: Session = Depends(get_db), user: models.User = Depends(get_current_user)):
    """Get all notifications for the current user."""
    notifications = db.query(models.Notification).filter(
        models.Notification.user_id == user.id
    ).order_by(models.Notification.timestamp.desc()).limit(50).all()

    unread_count = db.query(models.Notification).filter(
        models.Notification.user_id == user.id,
        models.Notification.read == False
    ).count()

    return {
        "unread_count": unread_count,
        "data": [
            {
                "id": n.id,
                "title": n.title,
                "message": n.message,
                "type": n.type,
                "read": n.read,
                "timestamp": n.timestamp
            } for n in notifications
        ]
    }

@app.post("/notifications/{notification_id}/read")
def mark_notification_read(notification_id: int, db: Session = Depends(get_db), user: models.User = Depends(get_current_user)):
    """Mark a single notification as read."""
    notification = db.query(models.Notification).filter(
        models.Notification.id == notification_id,
        models.Notification.user_id == user.id
    ).first()
    if not notification:
        raise HTTPException(status_code=404, detail="Notification not found")
    notification.read = True
    db.commit()
    return {"status": "ok"}

@app.post("/notifications/read-all")
def mark_all_read(db: Session = Depends(get_db), user: models.User = Depends(get_current_user)):
    """Mark all notifications as read for the current user."""
    db.query(models.Notification).filter(
        models.Notification.user_id == user.id,
        models.Notification.read == False
    ).update({"read": True})
    db.commit()
    return {"status": "ok"}


# ------------------------------------------------------------------
# Device management endpoints
# ------------------------------------------------------------------

@app.post("/devices/register")
def register_device(
    payload: schemas.DeviceRegister,
    db: Session = Depends(get_db),
    user: models.User = Depends(get_current_user)
):
    """Register a new device and generate an API key for the current user."""
    api_key = f"mg_{secrets.token_hex(24)}"
    new_device = models.Device(
        user_id=user.id,
        device_name=payload.device_name or "ESP32 Gateway",
        api_key=api_key
    )
    db.add(new_device)
    db.commit()
    db.refresh(new_device)
    return {
        "id": new_device.id,
        "device_name": new_device.device_name,
        "api_key": new_device.api_key,
        "last_seen": new_device.last_seen,
        "created_at": new_device.created_at
    }


@app.get("/devices/my")
def get_my_devices(db: Session = Depends(get_db), user: models.User = Depends(get_current_user)):
    """Get all devices for the current user."""
    devices = db.query(models.Device).filter(
        models.Device.user_id == user.id
    ).order_by(models.Device.created_at.desc()).all()
    return {
        "data": [
            {
                "id": str(d.id),
                "device_name": d.device_name,
                "api_key": d.api_key,
                "last_seen": d.last_seen,
                "created_at": d.created_at
            } for d in devices
        ]
    }


@app.post("/devices/{device_id}/regenerate-key")
def regenerate_device_key(
    device_id: int,
    db: Session = Depends(get_db),
    user: models.User = Depends(get_current_user)
):
    """Regenerate the API key for a device."""
    device = db.query(models.Device).filter(
        models.Device.id == device_id,
        models.Device.user_id == user.id
    ).first()

    if not device:
        raise HTTPException(status_code=404, detail="Device not found")
    device.api_key = f"mg_{secrets.token_hex(24)}"
    db.commit()
    db.refresh(device)
    return {
        "id": device.id,
        "device_name": device.device_name,
        "api_key": device.api_key,
        "last_seen": device.last_seen,
        "created_at": device.created_at
    }


@app.delete("/devices/{device_id}")
def delete_device(
    device_id: int,
    db: Session = Depends(get_db),
    user: models.User = Depends(get_current_user)
):
    """Delete a device."""
    device = db.query(models.Device).filter(
        models.Device.id == device_id,
        models.Device.user_id == user.id
    ).first()
    if not device:
        raise HTTPException(status_code=404, detail="Device not found")
    db.delete(device)
    db.commit()
    return {"status": "ok"}
