/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_916176_105_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_916176_2[] = { "High_Anthracnose_Risk", "High_Mildew_Risk", "Stable" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_916176_104_axes[] = { 0, 1 };
const uint32_t ei_dsp_config_916176_104_axes_size = 2;
ei_dsp_config_raw_t ei_dsp_config_916176_104 = {
    104, // uint32_t blockId
    1, // int implementationVersion
    2, // int length of axes
    1.0f // float scale-axes
};

const float ei_dn_standard_scaler_mean_916176_104[48] = { 19.91418035360896, 59.72464751257685, 19.912860858952136, 59.71965426982582, 19.926777130277287, 59.586032443613675, 19.917698993387564, 59.61369240208464, 19.891414696695435, 59.75480075322097, 19.899507584998005, 59.733048612177164, 19.90672083390925, 59.74456194032673, 19.916256357967477, 59.68912568250062, 19.926794720568513, 59.580163115770524, 19.913824811609256, 59.62673683186638, 19.906206929289397, 59.69195631236614, 19.90525688510978, 59.71296960581029, 19.893434230917194, 59.77129075075857, 19.900225240357067, 59.79651736441336, 19.916798063770806, 59.777231454010334, 19.924503898889057, 59.74795161931134, 19.90819497682275, 59.831843042608554, 19.916111940736926, 59.82256554953235, 19.927741069847393, 59.81613326492148, 19.925436346066157, 59.761567595305365, 19.94033782738854, 59.5744165414492, 19.946829728053373, 59.48790563520288, 19.918064765406694, 59.60296120197315, 19.913719236976576, 59.64222747351736 };
const float ei_dn_standard_scaler_scale_916176_104[48] = { 0.24454491952949742, 0.04146745493199534, 0.24377792549019073, 0.04152406424279491, 0.24338906799528, 0.041573431705264396, 0.2425040937709097, 0.04165128860516601, 0.24227037233488954, 0.04175598755923151, 0.24226354440983666, 0.04167749841271129, 0.2428754964182099, 0.04175562861512969, 0.2434435848508686, 0.041830375507887756, 0.24145509420156466, 0.041777563007317234, 0.24052055482342188, 0.04173478350243688, 0.2388759671959129, 0.04159086276739904, 0.23786199336844832, 0.04155539091936818, 0.23707686562077782, 0.041487077082989744, 0.23759998234365717, 0.04139756341237389, 0.2376393013811048, 0.04132450172412713, 0.23791927835643997, 0.041363412606268996, 0.23843060337720728, 0.041299474084776175, 0.24001179180315918, 0.041267268942631614, 0.241730850404993, 0.04114620345534126, 0.24229318314248124, 0.04118854916188763, 0.24299964209397254, 0.041200089775377854, 0.243374281074788, 0.04125329808824719, 0.24390819915019357, 0.04130923873094623, 0.24371259437393475, 0.04134659004437909 };
const float ei_dn_standard_scaler_var_916176_104[48] = { 16.72178790353302, 581.5475592622065, 16.827176346390438, 579.9630050188003, 16.88098813669223, 578.5864382445475, 17.004421091225673, 576.4254081401722, 17.03724569711228, 573.5383742732668, 17.038206061795396, 575.700640623466, 16.952454891966426, 573.548234936765, 16.873428312538262, 571.500314269562, 17.152493163809655, 572.9461352220646, 17.28604367769569, 574.1213139043175, 17.524881216200992, 578.1015594969763, 17.674612122828005, 579.0889203353162, 17.79187203619329, 580.997580028269, 17.71361462234634, 583.5128707435551, 17.707753431425825, 585.5779953416516, 17.666101941903374, 584.4767980396822, 17.590411708762048, 586.2879354021272, 17.359405246791855, 587.2033753803497, 17.113381825319586, 590.6639448531605, 17.034037888832962, 589.4500528760308, 16.935137694713358, 589.1198758048549, 16.883039507210384, 587.601167671926, 16.809206040864947, 586.0107955759879, 16.83619915101566, 584.9525034043326 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_916176_104 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_916176_104,
    .mean_data_len = 48,
    .scale_data = (float *)ei_dn_standard_scaler_scale_916176_104,
    .scale_data_len = 48,
    .var_data = (float *)ei_dn_standard_scaler_var_916176_104,
    .var_data_len = 48
};
ei_data_normalization_t ei_data_normalization_config_916176_104 = {
    (void *) &ei_data_normalization_standard_scaler_config_916176_104, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_916176_2_size = 1;
ei_model_dsp_t ei_dsp_blocks_916176_2[ei_dsp_blocks_916176_2_size] = {
    { // DSP block 104
        104,
        48, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_916176_104, // pointer to config struct
        ei_dsp_config_916176_104_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_916176_104_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_916176_104, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_916176_105 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_916176_105_init,
    .model_invoke = &tflite_learn_916176_105_invoke,
    .model_reset = &tflite_learn_916176_105_reset,
    .model_input = &tflite_learn_916176_105_input,
    .model_output = &tflite_learn_916176_105_output,
};

const uint8_t ei_output_tensors_indices_916176_105[1] = { 0 };
const uint8_t ei_output_tensors_size_916176_105 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_916176_105 = {
    .implementation_version = 1,
    .block_id = 105,
    .output_tensors_indices = ei_output_tensors_indices_916176_105,
    .output_tensors_size = ei_output_tensors_size_916176_105,
    .quantized = 0,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_916176_105,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_916176_2_size = 1;
const uint32_t ei_learning_block_916176_105_inputs[1] = { 104 };
const uint8_t ei_learning_block_916176_105_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_916176_2[ei_learning_blocks_916176_2_size] = {
    {
        105,
        &run_nn_inference,
        (void*)&ei_learning_block_config_916176_105,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_916176_105_inputs,
        ei_learning_block_916176_105_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_916176_2_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_916176_2[ei_postprocessing_blocks_916176_2_size] = {
    {
        .block_id = 105,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 105
    },
};

const uint8_t freeform_outputs_916176_2_size = 0;

uint32_t *freeform_outputs_916176_2 = nullptr;

const ei_impulse_t impulse_916176_2 = {
    .project_id = 916176,
    .project_owner = "University Program- Bahir Dar Institute of technology, Bahir Dar University: Embedded Systems, Machine Learning, IoT, IIoT",
    .project_name = "forcasting",
    .impulse_id = 2,
    .impulse_name = "impulse #2",
    .deploy_version = 2,

    .nn_input_frame_size = 48,
    .raw_sample_count = 24,
    .raw_samples_per_frame = 2,
    .dsp_input_frame_size = 24 * 2,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 3600000,
    .frequency = 0.0002777777777777778,

    .dsp_blocks_size = ei_dsp_blocks_916176_2_size,
    .dsp_blocks = ei_dsp_blocks_916176_2,

    .learning_blocks_size = ei_learning_blocks_916176_2_size,
    .learning_blocks = ei_learning_blocks_916176_2,

    .postprocessing_blocks_size = ei_postprocessing_blocks_916176_2_size,
    .postprocessing_blocks = ei_postprocessing_blocks_916176_2,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "temperature + humidity",
    .slice_size = (24/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_916176_2,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_916176_2_size,
    .freeform_outputs = freeform_outputs_916176_2
};

ei_impulse_handle_t impulse_handle_916176_2 = ei_impulse_handle_t( &impulse_916176_2 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_916176_2;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_916176_2;
const auto ei_dsp_blocks_size = ei_dsp_blocks_916176_2_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_916176_2;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
